CREATE TABLE "VIJAY"."CONTACT_DETAILS" 
   (	"CONTACT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CONTACT_NAME" VARCHAR2(50 BYTE), 
	"CONTACT_EMAIL" VARCHAR2(50 BYTE), 
	"CONTACT_NUMBER" NUMBER(10,0), 
	 CONSTRAINT "CONTACT_DETAILS_PK" PRIMARY KEY ("CONTACT_ID")